name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Atlassian SDK
        uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
      - name: Package the App
        run: |
          atlas-package
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          name: Compiled Plugin OBR
          path: target/*.obr
